version: '2.2'
services:
  thecloudbee01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: thecloudbee01
    environment:
      - node.name=thecloudbee01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=thecloudbee02,thecloudbee03
      - cluster.initial_master_nodes=thecloudbee01,thecloudbee02,thecloudbee03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  thecloudbee02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: thecloudbee02
    environment:
      - node.name=thecloudbee02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=thecloudbee01,thecloudbee03
      - cluster.initial_master_nodes=thecloudbee01,thecloudbee02,thecloudbee03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
  thecloudbee03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: thecloudbee03
    environment:
      - node.name=thecloudbee03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=thecloudbee01,thecloudbee02
      - cluster.initial_master_nodes=thecloudbee01,thecloudbee02,thecloudbee03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
