name: Update GIST on commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# https://github.com/marketplace/actions/gist-sync
jobs:
    gist-sync:
      name: gist-sync
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: popsiclestick/gist-sync-action@v1.2.0
          id: sync
          with:
            auth: ${{ secrets.GIST_TOKEN }}
            gist_url: https://gist.github.com/thecloudbee/b35adb2c30d2f2db9a54520128813be1
            gist_title: thecloudbee-2021-01-01-first-cft-1-simplest.yaml
            github_file: thecloudbee_blog/code_snippets/2021-01-01/cloudformation/first-cft-1-simplest.yaml
        - uses: popsiclestick/gist-sync-action@v1.2.0
          id: sync1
          with:
            auth: ${{ secrets.GIST_TOKEN }}
            gist_url: https://gist.github.com/0641a4b1052cd019f9781c8cbb642fc3
            gist_title: thecloudbee-2021-01-01-first-cft-2-separate-variables.yaml
            github_file: thecloudbee_blog/code_snippets/2021-01-01/cloudformation/first-cft-2-separate-variables.yaml
        - uses: popsiclestick/gist-sync-action@v1.2.0
          id: sync2
          with:
            auth: ${{ secrets.GIST_TOKEN }}
            gist_url: https://gist.github.com/aa1db06e7a835dd4e3dd6f2ba60fa860
            gist_title: thecloudbee-2021-01-01-first-cft-3-options.yaml
            github_file: thecloudbee_blog/code_snippets/2021-01-01/cloudformation/first-cft-3-options.yaml
        - uses: popsiclestick/gist-sync-action@v1.2.0
          id: sync3
          with:
            auth: ${{ secrets.GIST_TOKEN }}
            gist_url: https://gist.github.com/thecloudbee/abbdfdb5e421cd6361d68e8663691276
            gist_title: thecloudbee-2021-01-07-environment-example-with-instance-type.yaml
            github_file: thecloudbee_blog/code_snippets/2021-01-07/cloudformation/environment-example-with-instance-type.yaml
