name: Update GIST on commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# https://github.com/marketplace/actions/gist-sync
jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync5
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/aeb2439bf825d22b2a7637723d051464
          gist_title: thecloudbee-2021-01-18-custom-analyzer-query.sh
          github_file: thecloudbee_blog/code_snippets/2021-01-18/elasticsearch/custom-analyzer-query.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync6
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/44e5ad52c586f5f2abbb66c95b94aa2c
          gist_title: thecloudbee-2021-01-18-elasticsearch-index-query.sh
          github_file: thecloudbee_blog/code_snippets/2021-01-18/elasticsearch/elasticsearch-index-query.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync4
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/thecloudbee/59c7d12ab56bb2f1af95723a31d195a2
          gist_title: thecloudbee-2021-01-11-run-terraform-with-var-file.sh
          github_file: thecloudbee_blog/code_snippets/2021-01-11/terraform/run.sh
