name: Update GIST on commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# https://github.com/marketplace/actions/gist-sync
jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync1
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/thecloudbee/d41e716bf94202683bfef4cd29d1da91
          gist_title: 2021-02-08-es-rollover-index.sh
          github_file: thecloudbee_blog/code_snippets/2021-02-08/elasticsearch/rollover-index.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync2
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/thecloudbee/1f1c352aa23fd939bf2afa9d8b33e1bd
          gist_title: 2021-02-08-es-shrink-index.sh
          github_file: thecloudbee_blog/code_snippets/2021-02-08/elasticsearch/shrink-index.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync10
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/thecloudbee/0e53b158bab8aeb70c932e6b8e9e7f2b
          gist_title: 2021-01-25-ansible-hosts.yml
          github_file: thecloudbee_blog/code_snippets/2021-01-25/ansible/hosts/hosts
